import { Box } from "@chakra-ui/react"
import Head from "next/head"
import React from "react"
import Logo from "~/components/logo"
import { RunicNavigation } from "~/components/runic-navigation"

const Home = () => {
  const [activeIndex, setActiveIndex] = React.useState(0)

  return (
    <>
      <Head>
        <title>Create T3 AppTest</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="background portal-grid grid min-h-screen grid-cols-2">
        <Box className="top-left-container">
          {/* bg-green-500 opacity-50 */}
          <Logo />
        </Box>
        <Box
          display="flex"
          className="bottom-container"
          flexDirection={"column"}
        >
          {/* <Box
            background={"blue"}
            // flex="1"
            height="20px"
            justifyContent={"flex-end"}
            justifySelf={"flex-end"}
            alignContent={"flex-end"}
          ></Box> */}
        </Box>
        <RunicNavigation
          activeIndex={activeIndex}
          setActiveIndex={setActiveIndex}
        />
      </main>
    </>
  )
}

export default Home
