import { Button } from "@chakra-ui/react"
import Head from "next/head"
import RunicNavigation from "~/components/runic-navigation"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 AppTest</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="background portal-grid grid min-h-screen">
        <div className="row-span-1 bg-blue-500 opacity-35"></div>
        <RunicNavigation />
        <div className="row-span-1 bg-red-500 opacity-35">
          <Button>Test</Button>
        </div>
      </main>
    </>
  )
}
